Update README.md
Flutterando/triple_pattern pull request #111
Opened 2023-02-23 17:24 UTC by Joao-Fialho

2023-02-23 18:22 UTC, CristovoXDGM reviewed
Ficou massa, porém , por questão de padronizar, eu colocaria tudo para markdown, ao inves de html como está agora. E adiciona uma descrição do que se trata o PR @Joao-Fialho

2023-02-23 20:38 UTC, CristovoXDGM reviewed
lgtm

2023-02-23 20:54 UTC, CristovoXDGM reviewed
lgtm

2023-02-24 11:15 UTC, CristovoXDGM submitted a review, later dismissed

2023-02-24 11:58 UTC, AlvaroVasconcelos requested changes

2023-02-24 11:58 UTC, AlvaroVasconcelos commented on README.md
> +- Join and modify translations in our [Crowdin Translation Project](https://crowdin.com/project/apitablecode/invite?h=f48bc26f9eb188dcd92d5eb4a66f2c1f1555185)
project crowdin apitablecode ?

2023-02-24 11:58 UTC, AlvaroVasconcelos commented on README.md
> +- Create [Issues](https://github.com/flutterando-readme-template/flutterando-readme-template/issues/new/choose)
Issue Flutterando?

2023-02-24 14:45 UTC, CristovoXDGM reviewed
👍🏻

2023-02-27 18:34 UTC, merged